<!DOCTYPE html>
<html lang="en" layout-fill>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Andy</title>

    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>

    <script src="node_modules/@angular/core/bundles/core.umd.js"></script>
    <script src="node_modules/@angular/common/bundles/common.umd.js"></script>
    <script src="node_modules/@angular/compiler/bundles/compiler.umd.js"></script>
    <script src="node_modules/@angular/platform-browser/bundles/platform-browser.umd.js"></script>
    <script src="node_modules/@angular/animations/bundles/animations.umd.js"></script>
    <script src="node_modules/@angular/animations/bundles/animations-browser.umd.js"></script>
    <script src="node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js"></script>
    <script src="node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-bidi.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-platform.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-scrolling.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-portal.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-overlay.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-coercion.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-rxjs.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-a11y.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-collections.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-observers.umd.js"></script>
    <script src="node_modules/@angular/forms/bundles/forms.umd.js"></script>
    <script src="node_modules/@angular/http/bundles/http.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-stepper.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-table.umd.js"></script>
    <script src="node_modules/@angular/flex-layout/bundles/flex-layout.umd.js"></script>
    <script src="node_modules/@angular/animations/bundles/animations.umd.js"></script>
    <script src="node_modules/@angular/material/bundles/material.umd.js"></script>

    <link href="node_modules/@angular/material/prebuilt-themes/pink-bluegrey.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src='Component.js'></script>
    <script src='Module.js'></script>
    <script src='App.js'></script>

    <link href="App.css" rel="stylesheet">

    <base href="<?=PATH; ?>">
</head>
<body ng-cloak>
<app></app>
</body>
</html>
