<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- jQuery -->
    <script src="vendor/components/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
    <script src="vendor/twbs/bootstrap/assets/js/vendor/popper.min.js"></script>
    <script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Custom -->
    <!-- <script src="<?= Application::getURL("jQuery.js"); ?>"></script> -->
    <link rel="stylesheet" href="<?= PATH ?>Style.css">
    <!-- JIRA -->
    <script type="text/javascript" src="http://localhost:8080/s/53a6b67871465ed7b4838db208cf960f-T/-6pq3en/74002/b6b48b2829824b869586ac216d119363/2.0.23/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=a76297e0"></script>
    <!-- Angular -->
    <script src="node_modules/angular/angular.js"></script>
    <script src="node_modules/angular-aria/angular-aria.js"></script>
    <script src="node_modules/angular-animate/angular-animate.js"></script>
    <script src="node_modules/angular-material/angular-material.js"></script>
    <script src="node_modules/angular-route/angular-route.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.4/angular-material.min.css">

    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>

    <script src="node_modules/@angular/core/bundles/core.umd.js"></script>
    <script src="node_modules/@angular/common/bundles/common.umd.js"></script>
    <script src="node_modules/@angular/compiler/bundles/compiler.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk.umd.js"></script>
    <script src="node_modules/@angular/cdk/bundles/cdk-bidi.umd.js"></script>
    <script src="node_modules/@angular/platform-browser/bundles/platform-browser.umd.js"></script>
    <script src="node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"></script>
    <script src="node_modules/@angular/material/bundles/material.umd.js"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <script>
        // Include app dependency on ngMaterial
        // angular.module('App', ['ngRoute']);
        angular.module('App', ['ngRoute', 'ngMaterial'])
            .controller("MyController", MyController)
            .controller("Me", Me)

                .config(function ($routeProvider, $locationProvider) {
                $routeProvider
                    .when(':a*', {
                        // templateUrl: 'CMS/Index/Home',
                        template: '<div ng-include="templateUrl">Loading...</div>',
                        controller: 'Me'
                    })
                // configure html5 to get links working on jsfiddle
                $locationProvider.html5Mode(true);
            });
        function Me($scope, $route, $routeParams) {
            console.log($route);
            console.log($routeParams);
            $scope.templateUrl = $routeParams.a;
        }

        function MyController($scope, $mdSidenav) {
            $scope.openLeftMenu = function () {
                $mdSidenav('left').toggle();
            };
        }

        angular.element(document.body).ready(function () {
            angular.bootstrap(document.body, ['App']);
        });
        var HelloComponent = function () {

        };

        HelloComponent.annotations = [
            new ng.core.Component({
                selector: 'hello-app',
                template: 'Hello World!'
            })
        ];
        var AppModule = function () {

        };
        AppModule.annotations = [
            new ng.core.NgModule({
                imports: [ng.platformBrowser.BrowserModule],
                declarations: [HelloComponent],
                bootstrap: [HelloComponent]
            })
        ];
        document.addEventListener('DOMContentLoaded', function () {
            ng.platformBrowserDynamic
                .platformBrowserDynamic().bootstrapModule(AppModule);
        });
    </script>
    <base href="<?=BASE?>" target="_blank">
</head>
<body ng-controller="MyController" ng-cloak>
<div class="container-fluid">
    <div class="row">
        <div ng-include="'Layout/Index/Top'" class="col p-0" src="<?= Application::getURL("Layout/Index/Top"); ?>"></div>
    </div>
    <div class="row">
        <md-sidenav md-component-id="left" class="md-sidenav-left md-whiteframe-z2" ng-include="'Layout/Index/Left'">
        </md-sidenav>
        <div id="center" class="col p-3" ng-view>
            <hello-app></hello-app>
        </div>
        <div id="right" class="col-2 d-none" src="<?= Application::getURL("Layout/Index/Right"); ?>"></div>
    </div>
    <div class="row">
        <div id="bottom" class="col" src="<?= Application::getURL("Layout/Index/Bottom"); ?>">
        </div>
    </div>
</div>
</body>
</html>
