<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- jQuery -->
    <script src="vendor/components/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
 
    <script src="vendor/twbs/bootstrap/assets/js/vendor/popper.min.js"></script>
    <script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>






    <!-- Custom -->
    <script src="<?= Application::getURL("jQuery.js"); ?>"></script>
    <link rel="stylesheet" href="<?= PATH ?>Style.css">
    <!-- JIRA -->
    <script type="text/javascript" src="http://localhost:8080/s/53a6b67871465ed7b4838db208cf960f-T/-6pq3en/74002/b6b48b2829824b869586ac216d119363/2.0.23/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=a76297e0"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"> 
  </head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col p-0" src="<?= Application::getURL("Layout/Index/Top"); ?>"></div>
    </div>
    <div class="row">
        <div id="left" class="col-2 d-none" src="<?= Application::getURL("Layout/Index/Left"); ?>">
        </div>
        <div id="center" class="col p-3" src="CMS/Index/Home">
        </div>
        <div id="right" class="col-2 d-none" src="<?= Application::getURL("Layout/Index/Right"); ?>"></div>
    </div>
    <div class="row">
        <div id="bottom" class="col" src="<?= Application::getURL("Layout/Index/Bottom"); ?>">
        </div>
    </div>
</div>
</body>
</html>
