<div class="container-fluid h-100 md-content md-primary">
    <md-content>
        <h1 class="text-center"><a href="<? echo Application::getURL(); ?>">Brand</a></h1>
        <div class="text-white">
            <md-button class="md-raised md-primary" href="<?= PATH; ?>#!/User/Index/Account" ng-click="close()">My Account</md-button>
            <md-button class="md-raised md-primary" href="<?= PATH; ?>#!/User/Index/Settings">Settings</md-button>
            <md-button class="md-raised md-primary" href="<?= PATH; ?>#!/User/Index/Login">Login</md-button>
        </div>
    </md-content>
</div>