<div class="container-fluid h-100 bg-primary text-white">
    <h1 class="text-center">Menu</h1>
    <md-button class="md-raised md-primary" href="<?=PATH;?>/#!/User/Index/Account">My Account</md-button>
    <md-button class="md-raised md-primary" href="<?=PATH;?>/#!/User/Index/Settings">Settings</md-button>
    <md-button class="md-raised md-primary" href="<?=PATH;?>/#!/User/Index/Login">Login</md-button>
</div>