<mat-toolbar color="primary">
      <i class="material-icons align-middle">menu</i>
</mat-toolbar>
<nav class="navbar navbar-fixed navbar-dark bg-primary pl-0">
<div class="dropdowna">
  <button id="dropdownMenuButton" class="btn btn-link text-white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="openLeftMenu()">
      <i class="material-icons align-middle">menu</i>
  </button>
  <div class="navbar-brand align-middle">Brand</div>
</div>
</nav>