<nav class="navbar navbar-fixed navbar-dark bg-primary pl-0">
<div class="dropdown">
  <button id="dropdownMenuButton" class="btn btn-link text-white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="material-icons align-middle">menu</i> 
  </button>
  <div class="dropdown-menu bg-primary rounded-0 border-0" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="User/Index/Login">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
  <div class="navbar-brand align-middle">Brand</div>
</div>
</nav>