<md-toolbar color="primary" class="md-toolbar-tools justify-content-start md-whiteframe-z2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <md-button class="md-icon-button" ng-click="openLeftMenu()">
                    <i class="material-icons align-middle">menu</i>
                </md-button>
            </div>
            <div class="col-8">
                <div class="navbar-brand align-middle">Brand</div>
            </div>
            <div class="col-2">
                <md-button class="md-icon-button">
                    <i class="material-icons align-middle">account_circle</i>
                </md-button>
            </div>
        </div>
    </div>
</md-toolbar>
